-- Schema as it existed before authenticated order authorship.
-- No sample users or business data are inserted by migrations.
CREATE TABLE address (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street varchar(255),
    number varchar(255),
    complement varchar(255),
    neighborhood varchar(255),
    city varchar(255),
    state varchar(255),
    zip_code varchar(255)
);

CREATE TABLE client (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_type varchar(31) NOT NULL,
    name varchar(255),
    email varchar(255),
    birth_date date,
    address_id bigint UNIQUE REFERENCES address(id),
    cpf varchar(255) UNIQUE,
    cnpj varchar(255) UNIQUE,
    company_name varchar(255)
);

CREATE TABLE product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_type varchar(31) NOT NULL,
    name varchar(255),
    price double precision,
    description varchar(255),
    download_link varchar(255),
    weight double precision
);

CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moment timestamp(6),
    status varchar(255),
    client_id bigint REFERENCES client(id),
    address_id bigint UNIQUE REFERENCES address(id)
);

CREATE TABLE order_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity integer,
    price double precision,
    order_id bigint REFERENCES orders(id),
    product_id bigint REFERENCES product(id)
);

CREATE TABLE payment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_type varchar(31) NOT NULL,
    amount double precision,
    status varchar(255),
    payment_date timestamp(6),
    order_id bigint UNIQUE REFERENCES orders(id),
    bar_code varchar(255),
    due_date date,
    card_number varchar(255),
    card_holder varchar(255),
    installments integer,
    pix_key varchar(255),
    pix_holder_name varchar(255),
    transaction_id varchar(255),
    pix_key_type varchar(255)
);
