-- A nullable seller preserves orders made before authentication was introduced.
CREATE TABLE IF NOT EXISTS app_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    email varchar(254) NOT NULL UNIQUE,
    password_hash varchar(100) NOT NULL,
    role varchar(20) NOT NULL
);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS seller_id bigint;
CREATE INDEX IF NOT EXISTS idx_orders_seller_id ON orders(seller_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint c
        JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
        WHERE c.conrelid = 'orders'::regclass AND c.contype = 'f' AND a.attname = 'seller_id'
    ) THEN
        ALTER TABLE orders ADD CONSTRAINT fk_orders_seller
            FOREIGN KEY (seller_id) REFERENCES app_users(id);
    END IF;
END $$;
