name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: order_management
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: senha123
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d order_management"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"
          cache: maven

      - name: Test
        run: |
          chmod +x mvnw
          ./mvnw test
